# Generated by Django 4.0.2 on 2022-02-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=80)),
                ('response', models.CharField(max_length=80)),
                ('link', models.CharField(max_length=80)),
                ('next_choices', models.ManyToManyField(related_name='previous_choices', to='app.Choice')),
            ],
        ),
    ]
