# Generated by Django 4.0.2 on 2022-02-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='message',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='response',
        ),
        migrations.AddField(
            model_name='choice',
            name='response_en',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='response_fr',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='link',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='next_choices',
            field=models.ManyToManyField(blank=True, null=True, related_name='previous_choices', to='app.Choice'),
        ),
    ]
