# Generated by Django 4.0.2 on 2022-02-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_message_choice_title_remove_choice_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='next_choices',
            field=models.ManyToManyField(blank=True, related_name='previous_choices', to='app.Choice'),
        ),
    ]
