# Generated by Django 4.0.2 on 2022-02-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_chatbot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=80, null=True)),
                ('date', models.CharField(blank=True, max_length=80, null=True)),
                ('chatbot', models.CharField(blank=True, max_length=80, null=True)),
                ('chatbot_messages', models.CharField(blank=True, max_length=80, null=True)),
                ('user', models.CharField(blank=True, max_length=80, null=True)),
                ('user_messages', models.CharField(blank=True, max_length=80, null=True)),
                ('user_feedback', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(blank=True, max_length=80, null=True)),
                ('username', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('firstName', models.CharField(blank=True, max_length=80, null=True)),
                ('lastName', models.CharField(blank=True, max_length=80, null=True)),
                ('phone', models.CharField(blank=True, max_length=80, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('organization', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatbot',
            name='language',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
