# Generated by Django 4.0.2 on 2022-02-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_chat_chatbot_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=80, null=True)),
                ('lastName', models.CharField(blank=True, max_length=80, null=True)),
                ('phone', models.CharField(blank=True, max_length=80, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('organization', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='address',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='username',
        ),
    ]
