# Generated by Django 4.0.2 on 2022-03-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_client_user_remove_chat_address_remove_chat_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='response_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='response_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
