# Generated by Django 4.0.2 on 2022-03-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_choice_link_alter_choice_response_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='link',
            new_name='link_en',
        ),
        migrations.AddField(
            model_name='choice',
            name='link_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
