# Generated by Django 4.0.2 on 2022-04-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_link_choice_link_en_choice_link_fr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chatbot',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chatbot_messages',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='status',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_feedback',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_messages',
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='language',
            field=models.CharField(choices=[('fr', 'Francais'), ('en', 'English')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='language',
            field=models.CharField(choices=[('fr', 'Francais'), ('en', 'English')], max_length=2),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('chatbot', 'Chatbot'), ('user', 'User')], max_length=7, null=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('choice', 'Choice')], max_length=6, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('choice_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.chat')),
            ],
        ),
    ]
