# Generated by Django 4.0.2 on 2022-05-30 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_rename_address_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='agent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactRequests', to='app.chat'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactRequests', to='app.client'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='responseTime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('unclaimed', 'Unclaimed'), ('claimed', 'Claimed'), ('closed', 'Closed')], max_length=20),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
