# Generated by Django 4.0.2 on 2022-06-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demorequest',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='demorequest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='demorequest',
            name='service',
        ),
        migrations.AddField(
            model_name='demorequest',
            name='demo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demoRequests', to='app.demo'),
        ),
    ]
