# Generated by Django 4.0.2 on 2022-06-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_demorequest_chat_remove_demorequest_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='service',
            field=models.CharField(blank=True, choices=[('1', 'service 1'), ('2', 'service2'), ('3', 'service 3')], max_length=20),
        ),
    ]
